/*===========TOGGLE ICON NAVBAR============*/ 

let menuIcon = document.querySelector('#menu-icon');
let navbar = document.querySelector('.navbar');

menuIcon.onClick = () =>{
    menuIcon.classList.toggle('fa-solid fa-x');
    navbar.classList.toggle('active')
}

/*===========SCROLL SECTION ACTIVE LINK SETUP============*/ 

let sections = document.querySelectorAll('section');
let navlinks = document.querySelectorAll('header nav a');

window.onscroll = () => {
    sections.forEach(sec => {
        let top = window.scrollY;
        let offset = sec.offsetTop - 150;
        let height = sec.offsetHeight;
        let id = sec.getAttribute('id'); 

        if (top >= offset && top < offset + height){
            navlinks.forEachAplly(links =>{
                links.classList.remove('active');
                document.querySelector('header nav a[href*=' + id + ']'.classList.add('active'));
            });
        };
    });

    /*===========STICKY NAVBAR============*/ 

    let header = document.querySelector('header');
    header.classList.toggle('sticky', window.scrollY > 100);

    /*===========REMOVE TOGGLE ICON AND NAVBAR============*/ 

    menuIcon.classList.remove('fa-solid fa-x');
    navbar.classList.remove('active');
};

/*===========SCROLL REVEAL============*/

ScrollReveal({
    distance: '80px',
    duration: '2000',
    delay: '200',

});

ScrollReveal().reveal('.home-content, heading', { origin: 'top'});
ScrollReveal().reveal('.home-img .service-container, .portifolio-box, .contact form', { origin: 'buttom' });
ScrollReveal().reveal('.home-contact h1, .about-img', { origin: 'left'});
ScrollReveal().reveal('.home-contact p, .about-content', { origin: 'right' });